### ISSUE TITLE
Can't add file by URL

### ISSUE THREAD

**Issue by vitlav** [jbenet/http2ipfs-web#5]
I got  /ipfs/undefined/HASH in a browser
and 
{"Message":"This command can't be called directly. Try one of its subcommands.","Code":1}
for 
http://127.0.0.1:5001/api/v0/object/patch?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn&arg=add-link&arg=7919478b9c0fc416a351b6b18a1bf3.jpg&arg=Qmca24TB7APCUseKw4bz4dr8DCQAPGgCYTd7u3Z1sVjPhV&stream-channels=true
request
after try to add some URL.

tried with
https://ipfs.io/ipfs/QmZTEDF8yN3dMGcYqtyTzuR8PFsTqmLLBxsVZ4jzV2a1rd/

**Comment by raspher** [comment]
i think all is going fine but resolve hash, which is undefined. why it is undefined?

same problem here

**Comment by jfmherokiller** [comment]
i fixed the issue with the undefined link and have uploaded my fixed version here http://localhost:8080/ipfs/QmcMbnN3Lw3L8dxYEYFrqVLej28L3vgUHS1DbAm7QERsZY/
and here 
https://ipfs.io/ipfs/QmcMbnN3Lw3L8dxYEYFrqVLej28L3vgUHS1DbAm7QERsZY/

**Comment by JayBrown** [comment]
Still getting "undefined". Tried adding a wikipedia article, but it doesn't work. Local node is writable; always running with `export IPFS_REUSEPORT=false ; ipfs daemon --writable`

**Comment by adrodanevik** [comment]
Me too. But there is no command ~/ipfs --writeable (nor writable)

**Comment by vitlav** [comment]
Still getting...
![image](https://user-images.githubusercontent.com/3002368/37208204-81d9793a-23b1-11e8-9a3e-5c72d29095e8.png)

**Comment by blambin** [comment]
me to get  undefined
